[settings]
active_cell_color = "pink"
column_header_background_color = "#002200"
column_header_foreground_color = "yellow"
cursor_positions_json = "{\"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob.tss\": \"19,0\", \"__untitled__\": \"0,0\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/example.tss\": \"20,0\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob2.tss\": \"0,0\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob3.tss\": \"20,1\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/testing.tss\": \"27,1\"}"
date_format = "date:european"
formula_coloration = "on"
formula_foreground_color = "green"
language = "en"
protected_background_color = "palepink"
protected_foreground_color = "black"
recent_files_json = "[\"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob3.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/testing.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob2.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/example.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/tests.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob4.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/AGENTS.md\", \"/home/xircon/scripts/tui-ss/sheets/gui-test.tss\"]"
row_header_background_color = "#002200"
row_header_foreground_color = "yellow"
sheet_background_color = "none"
sheet_foreground_color = "none"
theme_name = "blue"
tui_background_color = "darkgreen"
tui_foreground_color = "black"
