[settings]
active_cell_color = "orange"
column_header_background_color = "#000066"
column_header_foreground_color = "yellow"
cursor_positions_json = "{\"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob.tss\": \"6,1\"}"
date_format = "date:european"
formula_coloration = "on"
formula_foreground_color = "green"
language = "en"
protected_background_color = "palepink"
protected_foreground_color = "black"
recent_files_json = "[\"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/tests.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob3.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob4.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/copyprob2.tss\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/AGENTS.md\", \"/home/xircon/dmnts/twotb/scripts/tui-ss/example.tss\", \"/home/xircon/scripts/tui-ss/sheets/gui-test.tss\"]"
row_header_background_color = "#000066"
row_header_foreground_color = "yellow"
theme_name = "blue"
tui_background_color = "lightblue"
tui_foreground_color = "black"
