#!/usr/bin/env python3
"""Slash command parsing."""

from __future__ import annotations

import shlex
from dataclasses import dataclass


@dataclass(slots=True)
class Command:
    name: str
    args: list[str]


ALIASES = {
    "a": "arrange",
    "b": "blank",
    "c": "copy",
    "d": "delete",
    "find": "find",
    "fill": "fill",
    "h": "help",
    "hide": "hide",
    "q": "quit",
    "redo": "redo",
    "replace": "replace",
    "raw": "raw",
    "e": "edit",
    "f": "format",
    "g": "global",
    "i": "insert",
    "j": "justify",
    "l": "load",
    "m": "move",
    "o": "output",
    "p": "protect",
    "r": "replicate",
    "s": "save",
    "saveas": "saveas",
    "t": "title",
    "duplicate": "duplicate",
    "unhide": "unhide",
    "u": "unprotect",
    "w": "window",
    "x": "execute",
    "z": "zap",
    "go": "goto",
    "open": "load",
    "clear": "blank",
    "?": "help",
    "tab": "tab",
}

COMMAND_MENU_OPTIONS = [
    "arrange",
    "blank",
    "copy",
    "delete",
    "edit",
    "execute",
    "fill",
    "find",
    "format",
    "global",
    "goto",
    "help",
    "insert",
    "justify",
    "load",
    "move",
    "output",
    "protect",
    "quit",
    "redo",
    "replicate",
    "replace",
    "raw",
    "save",
    "tab",
    "duplicate",
    "hide",
    "title",
    "unhide",
    "unprotect",
    "zap",
    "tab",
]

ADVANCED_COMMAND_MENU_OPTIONS = [
    "edit",
    "execute",
    "help",
    "output",
    "redo",
    "replace",
    "zap",
]

COMMAND_DESCRIPTIONS = {
    "arrange": "Sort rows in the selected range.",
    "blank": "Clear values and formatting from cells.",
    "copy": "Copy a source range to a destination.",
    "delete": "Delete rows or columns.",
    "edit": "Open settings.",
    "execute": "Run commands from a command file.",
    "find": "Find matching text in the sheet.",
    "format": "Apply number, date, text, or background formats.",
    "global": "Change default or per-column widths.",
    "goto": "Jump directly to a cell.",
    "help": "Open command, key, or formula help.",
    "hide": "Hide rows or columns.",
    "insert": "Insert rows or columns at the current position.",
    "justify": "Set left, centre, or right alignment.",
    "load": "Browse for and open a sheet in a new tab.",
    "move": "Move rows or columns to a new position.",
    "output": "Export to screen, text, CSV, TSV, or PDF.",
    "protect": "Protect the selected cells.",
    "quit": "Close the current tab or exit the app.",
    "redo": "Redo the last undone action.",
    "replicate": "Replicate formulas or values to a destination.",
    "replace": "Replace raw text in cells.",
    "raw": "Toggle raw formula view for the active cell.",
    "save": "Save, save-as, or save and quit.",
    "duplicate": "Duplicate rows or columns.",
    "fill": "Fill selections down or right, including smart series.",
    "title": "Freeze title rows and columns.",
    "unhide": "Unhide rows or columns.",
    "unprotect": "Remove protection from cells.",
    "zap": "Clear the whole current workspace.",
    "tab": "Rename, duplicate, close, or reorder tabs.",
}

HELP_TOPICS = ["commands", "formulas", "keys"]
LANGUAGE_OPTIONS = ["english", "francais", "deutsch", "italiano", "espanol", "nederlands"]

LANGUAGE_CODES = {
    "english": "en",
    "francais": "fr",
    "deutsch": "de",
    "italiano": "it",
    "espanol": "es",
    "nederlands": "nl",
}

COMMAND_HELP_LINES = [
    "/A range [col] [desc]  Sort rows in a range by column offset.",
    "/B [range]             Blank a cell or range (defaults to selection).",
    "/C src dst             Copy a range to a destination (defaults to selection).",
    "/D row|col index [n]   Delete rows or columns (defaults to selection).",
    "/E                     Open settings.",
    "/F                     Open the format menu.",
    "/F DATE                Set the whole-sheet date format.",
    "/F TIME                Set time format (24h, 24h-seconds, 12h, 12h-seconds).",
    "/FIND text [range]     Find next matching cell.",
    "/FILL down|right [series] [range]  Fill a selection or extend a series.",
    "/G width n             Set global column width.",
    "/G width col n         Set one column width, for example /G width B 18.",
    "/H                     Open help topics.",
    "/I row|col index [n]   Insert rows or columns.",
    "/HIDE row|col range    Hide rows or columns.",
    "/J left|centre|right [range]  Justify left, centre, or right.",
    "/L                     Browse recent files or open the file picker for .tss/.csv/.tsv sheets.",
    "/M row|col a b [n]     Move rows or columns.",
    "/O screen|file path    Output to screen, .txt, .csv, .tsv, or .pdf.",
    "/P [range]             Protect cells from editing (defaults to selection).",
    "/Q                     Quit.",
    "/REDO                  Redo the last undone action.",
    "/R src dst             Replicate formulas/contents to destination.",
    "/REPLACE old new [range] Replace raw cell text.",
    "/RAW                  Toggle raw formula view (Esc to close).",
    "/S [file]              Save file, or open save/save-as/save-quit menu.",
    "/SAVEAS file           Save sheet to a new file.",
    "/TAB                   Manage tabs (rename, duplicate, close, move).",
    "/DUPLICATE row|col range  Duplicate rows or columns after the selection.",
    "/T rows [cols]         Freeze title rows and columns.",
    "/UNHIDE row|col range  Unhide rows or columns.",
    "/U [range]             Remove protection (defaults to selection).",
    "/W                     Open command help.",
    "/X file                Execute commands from a file.",
    "/Z                     Clear the whole workspace.",
    "/GO cell               Jump to a cell.",
    "/TAB                   Manage tabs (rename, duplicate, close, move).",
]

KEY_HELP_LINES = [
    "Arrow keys or hjkl     Move the active cell.",
    "Shift+arrow keys       Extend a rectangular selection.",
    "Shift+Space            Select the current row when the terminal supports it.",
    "Ctrl+Space             Select the current column.",
    "Enter                  Edit current cell, store, then move down.",
    "Delete                 Clear current cell contents.",
    "Ctrl+C                 Copy the current cell or selection.",
    "Ctrl+V or Ctrl+Y       Paste the copied cell or selection.",
    "Ctrl+S                 Save the current sheet.",
    "Ctrl+Q                 Quit.",
    "Ctrl+Z                 Undo the last action.",
    "Ctrl+E or F2           Edit current cell in the formula bar.",
    "Ctrl+R                 Redo the last undone action.",
    "Ctrl+B                 Apply bold format.",
    "Ctrl+U                 Apply underline format.",
    "Ctrl+I                 Apply italic format.",
    "F1                     Toggle keybinding overlay.",
    "/                      Open the command menu.",
    "/H                     Open help topics.",
    "Esc                    Cancel prompt or menu.",
    "Alt+=                  Insert SUM of numeric cells above.",
    "Mouse click            Move active cell.",
    "Mouse drag             Select a rectangular range.",
    "Mouse wheel/touchpad   Scroll vertically.",
    "Mouse click tab        Switch open files.",
    "Click bottom-right cog Open settings.",
    "Click row/col header   Select the whole row/column; click again for actions.",
    "Selection stats        Bottom bar shows count/sum/avg for numeric cells.",
    "File picker: type text Filter visible items while browsing files.",
    "File picker: .         Toggle hidden files on or off.",
    "File picker: r         Rename selected file or folder.",
    "File picker: Delete    Delete selected file or folder.",
    "File picker: ..        Go to the parent folder.",
    "File picker: s         Cycle sort by name, time, or type.",
    "File picker: p         Type a path to open directly.",
    "File picker: n         Create a new folder.",
]

FORMULA_HELP_LINES = [
    "Math/Stats: ABS, AVERAGE, AVG, COS, COUNT, COUNTIF, INT, MAX, MIN, MOD, ROUND, SIN, SQRT, SUM, SUMIF, TAN",
    "Logical: AND, IF(condition, then_value, else_value), IFERROR, NOT, OR",
    "Text: CONCAT, LEFT, LEN, LOWER, MID, PROPER, RIGHT, TEXT, TRIM, UPPER, VALUE",
    "Data: HLOOKUP, INDEX, LOOKUP, MATCH, SUMIF, VLOOKUP, XLOOKUP",
    "Dates: DATE, TODAY, YEAR, MONTH, DAY, DATEDIFF, WEEKDAY",
    "Times: TIME, NOW, HOUR, MINUTE, SECOND, TIMEVALUE",
    "Sheet date display/input: /F DATE then choose european, uk, us, or ansi",
    "Formula entry: arrows point to cells, : starts a range, Enter accepts/closes brackets",
    'COUNTIF/SUMIF criteria can be exact values like "Fred" or operators like ">10", "<=5", "<>0".',
    "",
    "Examples:",
    "=SUM(A1:A10)",
    "=AND(A1>0, B1>0)",
    "=AVERAGE(B1:B5)",
    "=ROUND(C1/7, 2)",
    "=ABS(D1)",
    "=COS(0)",
    "=SIN(0)",
    "=MOD(A1, 7)",
    '=COUNTIF(A2:A10, "Fred")',
    "=IF(A1=10, 1, 0)",
    "=IF(B2<>0, B1/B2, 0)",
    '=IFERROR(VLOOKUP("Fred", A2:C10, 2), "missing")',
    '=CONCAT(LEFT(A1, 3), "-", RIGHT(B1, 2))',
    '=TEXT(TODAY(), "dd/mm/yyyy")',
    '=LOOKUP("Fred", A2:A10, B2:B10)',
    '=XLOOKUP("Fred", A2:A10, B2:B10, "missing")',
    '=SUMIF(B2:B10, ">10", C2:C10)',
    '=SUMIF(A2:A10, "Fred", B2:B10)',
    '=MATCH("Fred", A2:A10)',
    '=INDEX(B2:B10, 3)',
    '=TRIM("  hello   world  ")',
    '=UPPER("fred")',
    '=LOWER("FRED")',
    '=PROPER("bank account")',
    '=VLOOKUP("Fred", A2:C10, 2)',
    '=HLOOKUP("Q2", A1:D4, 3)',
    "=DATE(2026, 4, 5)",
    "=TODAY()",
    "=YEAR(A1)",
    "=MONTH(A1)",
    "=DAY(A1)",
    "=DATEDIFF(A1, B1)",
    "=WEEKDAY(A1)",
    "",
    "Absolute refs: $A$1  $A1  A$1",
]

TRANSLATIONS = {
    "fr": {
        "settings": "Parametres",
        "theme": "Theme",
        "date_format": "Format de date",
        "time_format": "Format d'heure",
        "active_cell": "Cellule active",
        "sheet_fg": "Feuille texte",
        "sheet_bg": "Feuille fond",
        "tui_fg": "TUI texte",
        "tui_bg": "TUI fond",
        "row_header_fg": "Entete ligne texte",
        "row_header_bg": "Entete ligne fond",
        "column_header_fg": "Entete colonne texte",
        "column_header_bg": "Entete colonne fond",
        "formula_colour": "Couleur formule",
        "protected_fg": "Protege texte",
        "protected_bg": "Protege fond",
        "language": "Langue",
        "settings_help_1": "Utilisez Haut/Bas pour choisir un parametre.",
        "settings_help_2": "Utilisez Gauche/Droite ou Entree pour changer la valeur choisie.",
        "settings_help_3": "Echap ferme les parametres.",
        "settings_closed": "Parametres fermes.",
        "commands": "Commandes",
        "formulas": "Formules",
        "keys": "Touches",
        "help": "Aide",
        "formula_help": "Aide Formules",
        "help_commands": "Aide: commandes",
        "help_formulas": "Aide: formules",
        "help_keys": "Aide: touches",
        "help_cancelled": "Aide annulee.",
        "save": "Enregistrer",
        "save_cancelled": "Enregistrement annule.",
        "save_as_cancelled": "Enregistrer sous annule.",
        "quit_cancelled": "Quitter annule.",
        "bye": "Au revoir.",
        "saved_and_exited": "Enregistre et quitte.",
        "exited_without_saving": "Quitte sans enregistrer.",
        "unsaved_quit": "Modifications non enregistrees. Quitter?",
        "save_quit": "enregistrer+quitter",
        "discard_quit": "abandonner+quitter",
        "command_cancelled": "Commande annulee.",
        "ready": "Pret.",
        "click_cog": "Cliquez sur l'engrenage en bas a droite pour ouvrir les parametres.",
    },
    "de": {
        "settings": "Einstellungen", "theme": "Thema", "date_format": "Datumsformat", "active_cell": "Aktive Zelle", "sheet_fg": "Blatt Text", "sheet_bg": "Blatt Hintergrund", "tui_fg": "TUI Text", "tui_bg": "TUI Hintergrund", "row_header_fg": "Zeilenkopf Text", "row_header_bg": "Zeilenkopf Hintergrund", "column_header_fg": "Spaltenkopf Text", "column_header_bg": "Spaltenkopf Hintergrund", "formula_colour": "Formelfarbe", "protected_fg": "Schutz Text", "protected_bg": "Schutz Hintergrund", "language": "Sprache",
        "time_format": "Zeitformat",
        "settings_help_1": "Mit Hoch/Runter eine Einstellung waehlen.", "settings_help_2": "Mit Links/Rechts oder Enter den Wert aendern.", "settings_help_3": "Esc schliesst die Einstellungen.",
        "settings_closed": "Einstellungen geschlossen.", "commands": "Befehle", "formulas": "Formeln", "keys": "Tasten", "help": "Hilfe", "formula_help": "Formelhilfe",
        "help_commands": "Hilfe: Befehle", "help_formulas": "Hilfe: Formeln", "help_keys": "Hilfe: Tasten", "help_cancelled": "Hilfe abgebrochen.",
        "save": "Speichern", "save_cancelled": "Speichern abgebrochen.", "save_as_cancelled": "Speichern unter abgebrochen.", "quit_cancelled": "Beenden abgebrochen.",
        "bye": "Tschuess.", "saved_and_exited": "Gespeichert und beendet.", "exited_without_saving": "Ohne Speichern beendet.",
        "unsaved_quit": "Ungespeicherte Aenderungen. Beenden?", "save_quit": "speichern+beenden", "discard_quit": "verwerfen+beenden", "command_cancelled": "Befehl abgebrochen.", "ready": "Bereit.",
        "click_cog": "Klicken Sie auf das Zahnrad unten rechts, um die Einstellungen zu oeffnen.",
    },
    "it": {
        "settings": "Impostazioni", "theme": "Tema", "date_format": "Formato data", "active_cell": "Cella attiva", "sheet_fg": "Foglio testo", "sheet_bg": "Foglio sfondo", "tui_fg": "TUI testo", "tui_bg": "TUI sfondo", "row_header_fg": "Intest. riga testo", "row_header_bg": "Intest. riga sfondo", "column_header_fg": "Intest. colonna testo", "column_header_bg": "Intest. colonna sfondo", "formula_colour": "Colore formula", "protected_fg": "Prot. testo", "protected_bg": "Prot. sfondo", "language": "Lingua",
        "time_format": "Formato ora",
        "settings_help_1": "Usa Su/Giu per scegliere un'impostazione.", "settings_help_2": "Usa Sinistra/Destra o Invio per cambiare il valore selezionato.", "settings_help_3": "Esc chiude le impostazioni.",
        "settings_closed": "Impostazioni chiuse.", "commands": "Comandi", "formulas": "Formule", "keys": "Tasti", "help": "Aiuto", "formula_help": "Aiuto formule",
        "help_commands": "Aiuto: comandi", "help_formulas": "Aiuto: formule", "help_keys": "Aiuto: tasti", "help_cancelled": "Aiuto annullato.",
        "save": "Salva", "save_cancelled": "Salvataggio annullato.", "save_as_cancelled": "Salva con nome annullato.", "quit_cancelled": "Uscita annullata.",
        "bye": "Ciao.", "saved_and_exited": "Salvato e uscito.", "exited_without_saving": "Uscito senza salvare.",
        "unsaved_quit": "Modifiche non salvate. Uscire?", "save_quit": "salva+esci", "discard_quit": "scarta+esci", "command_cancelled": "Comando annullato.", "ready": "Pronto.",
        "click_cog": "Fai clic sull'ingranaggio in basso a destra per aprire le impostazioni.",
    },
    "es": {
        "settings": "Configuracion", "theme": "Tema", "date_format": "Formato de fecha", "active_cell": "Celda activa", "sheet_fg": "Hoja texto", "sheet_bg": "Hoja fondo", "tui_fg": "TUI texto", "tui_bg": "TUI fondo", "row_header_fg": "Cab. fila texto", "row_header_bg": "Cab. fila fondo", "column_header_fg": "Cab. columna texto", "column_header_bg": "Cab. columna fondo", "formula_colour": "Color formula", "protected_fg": "Prot. texto", "protected_bg": "Prot. fondo", "language": "Idioma",
        "time_format": "Formato hora",
        "settings_help_1": "Usa Arriba/Abajo para elegir un ajuste.", "settings_help_2": "Usa Izquierda/Derecha o Intro para cambiar el valor seleccionado.", "settings_help_3": "Esc cierra la configuracion.",
        "settings_closed": "Configuracion cerrada.", "commands": "Comandos", "formulas": "Formulas", "keys": "Teclas", "help": "Ayuda", "formula_help": "Ayuda de formulas",
        "help_commands": "Ayuda: comandos", "help_formulas": "Ayuda: formulas", "help_keys": "Ayuda: teclas", "help_cancelled": "Ayuda cancelada.",
        "save": "Guardar", "save_cancelled": "Guardado cancelado.", "save_as_cancelled": "Guardar como cancelado.", "quit_cancelled": "Salida cancelada.",
        "bye": "Adios.", "saved_and_exited": "Guardado y salido.", "exited_without_saving": "Salio sin guardar.",
        "unsaved_quit": "Cambios sin guardar. Salir?", "save_quit": "guardar+salir", "discard_quit": "descartar+salir", "command_cancelled": "Comando cancelado.", "ready": "Listo.",
        "click_cog": "Haz clic en el engranaje inferior derecho para abrir configuracion.",
    },
    "nl": {
        "settings": "Instellingen", "theme": "Thema", "date_format": "Datumformaat", "active_cell": "Actieve cel", "sheet_fg": "Blad tekst", "sheet_bg": "Blad achtergrond", "tui_fg": "TUI tekst", "tui_bg": "TUI achtergrond", "row_header_fg": "Rijkop tekst", "row_header_bg": "Rijkop achtergrond", "column_header_fg": "Kolomkop tekst", "column_header_bg": "Kolomkop achtergrond", "formula_colour": "Formulekleur", "protected_fg": "Bescherm tekst", "protected_bg": "Bescherm achtergrond", "language": "Taal",
        "time_format": "Tijdformaat",
        "settings_help_1": "Gebruik Omhoog/Omlaag om een instelling te kiezen.", "settings_help_2": "Gebruik Links/Rechts of Enter om de gekozen waarde te wijzigen.", "settings_help_3": "Esc sluit de instellingen.",
        "settings_closed": "Instellingen gesloten.", "commands": "Commando's", "formulas": "Formules", "keys": "Toetsen", "help": "Help", "formula_help": "Formulehulp",
        "help_commands": "Help: commando's", "help_formulas": "Help: formules", "help_keys": "Help: toetsen", "help_cancelled": "Help geannuleerd.",
        "save": "Opslaan", "save_cancelled": "Opslaan geannuleerd.", "save_as_cancelled": "Opslaan als geannuleerd.", "quit_cancelled": "Afsluiten geannuleerd.",
        "bye": "Tot ziens.", "saved_and_exited": "Opgeslagen en afgesloten.", "exited_without_saving": "Afgesloten zonder op te slaan.",
        "unsaved_quit": "Niet-opgeslagen wijzigingen. Afsluiten?", "save_quit": "opslaan+afsluiten", "discard_quit": "verwerpen+afsluiten", "command_cancelled": "Commando geannuleerd.", "ready": "Gereed.",
        "click_cog": "Klik op het tandwiel rechtsonder om instellingen te openen.",
    },
}


def tr(language_code: str, key: str) -> str:
    if language_code == "en":
        english = {
            "settings": "Settings",
            "theme": "Theme",
            "date_format": "Date Format",
            "time_format": "Time Format",
            "active_cell": "Active Cell",
            "sheet_fg": "Sheet FG",
            "sheet_bg": "Sheet BG",
            "tui_fg": "TUI Fg",
            "tui_bg": "TUI Bg",
            "row_header_fg": "Row Header FG",
            "row_header_bg": "Row Header BG",
            "column_header_fg": "Column Header FG",
            "column_header_bg": "Column Header BG",
            "formula_colour": "Formula Colour",
            "protected_fg": "Protected FG",
            "protected_bg": "Protected BG",
            "language": "Language",
            "settings_help_1": "Use Up/Down to choose a setting.",
            "settings_help_2": "Use Left/Right or Enter to change the selected value.",
            "settings_help_3": "Esc closes settings.",
            "settings_closed": "Settings closed.",
            "commands": "Commands",
            "formulas": "Formulas",
            "keys": "Keys",
            "help": "Help",
            "formula_help": "Formula Help",
            "help_commands": "Help: commands",
            "help_formulas": "Help: formulas",
            "help_keys": "Help: keys",
            "help_cancelled": "Help cancelled.",
            "save": "Save",
            "save_cancelled": "Save cancelled.",
            "save_as_cancelled": "Save as cancelled.",
            "quit_cancelled": "Quit cancelled.",
            "bye": "Bye.",
            "saved_and_exited": "Saved and exited.",
            "exited_without_saving": "Exited without saving.",
            "unsaved_quit": "Unsaved changes. Quit?",
            "save_quit": "save+quit",
            "discard_quit": "discard+quit",
            "command_cancelled": "Command cancelled.",
            "ready": "Ready.",
            "click_cog": "Click the bottom-right cog to open settings.",
        }
        return english.get(key, key)
    return TRANSLATIONS.get(language_code, {}).get(key, tr("en", key))


def get_command_help_lines(language_code: str) -> list[str]:
    if language_code == "fr":
        return [
            "/A range [col] [desc]  Trier les lignes d'une plage par decalage de colonne.",
            "/B [range]             Vider une cellule ou une plage (selection par defaut).",
            "/C src dst             Copier une plage vers une destination (selection par defaut).",
            "/D row|col index [n]   Supprimer des lignes ou des colonnes (selection par defaut).",
            "/E                     Ouvrir les parametres.",
            "/F                     Ouvrir le menu de format.",
            "/F DATE                Definir le format de date pour toute la feuille.",
            "/F TIME                Definir le format d'heure (24h, 24h-seconds, 12h, 12h-seconds).",
            "/FIND text [range]     Trouver la cellule suivante correspondante.",
            "/G width n             Definir la largeur globale des colonnes.",
            "/G width col n         Definir la largeur d'une colonne, par ex. /G width B 18.",
            "/H                     Ouvrir les rubriques d'aide.",
            "/I row|col index [n]   Inserer des lignes ou des colonnes.",
            "/J left|centre|right [range]  Aligner a gauche, au centre ou a droite.",
            "/L                     Parcourir les recents ou ouvrir le selecteur pour .tss/.csv/.tsv.",
            "/M row|col a b [n]     Deplacer des lignes ou des colonnes.",
            "/O screen|file path    Sortir vers l'ecran, .txt, .csv, .tsv ou .pdf.",
            "/P [range]             Proteger des cellules contre la modification (selection par defaut).",
            "/Q                     Quitter.",
            "/REDO                  Retablir la derniere action annulee.",
            "/R src dst             Repliquer formules/contenu vers la destination.",
            "/REPLACE old new [range] Remplacer le texte brut dans les cellules.",
            "/S [file]              Enregistrer, ou ouvrir le menu enregistrer/enregistrer sous/enregistrer+quitter.",
            "/SAVEAS file           Enregistrer la feuille sous un nouveau fichier.",
            "/TAB                   Gerer les onglets (renommer, dupliquer, fermer, deplacer).",
            "/T rows [cols]         Figer les lignes et colonnes de titre.",
            "/U [range]             Retirer la protection (selection par defaut).",
            "/W                     Ouvrir l'aide des commandes.",
            "/X file                Executer les commandes depuis un fichier.",
            "/Z                     Effacer tout l'espace de travail.",
            "/GO cell               Aller a une cellule.",
        ]
    if language_code == "de":
        return [
            "/A range [col] [desc]  Zeilen eines Bereichs nach Spaltenversatz sortieren.",
            "/B [range]             Eine Zelle oder einen Bereich leeren (Standard: Auswahl).",
            "/C src dst             Einen Bereich an ein Ziel kopieren (Standard: Auswahl).",
            "/D row|col index [n]   Zeilen oder Spalten loeschen (Standard: Auswahl).",
            "/E                     Einstellungen oeffnen.",
            "/F                     Formatmenue oeffnen.",
            "/F DATE                Datumsformat fuer das ganze Blatt festlegen.",
            "/F TIME                Zeitformat festlegen (24h, 24h-seconds, 12h, 12h-seconds).",
            "/FIND text [range]     Naechste passende Zelle finden.",
            "/G width n             Globale Spaltenbreite festlegen.",
            "/G width col n         Breite einer Spalte festlegen, z. B. /G width B 18.",
            "/H                     Hilfethemen oeffnen.",
            "/I row|col index [n]   Zeilen oder Spalten einfuegen.",
            "/J left|centre|right [range]  Links, zentriert oder rechts ausrichten.",
            "/L                     Letzte Dateien oder Dateiwaehler fuer .tss/.csv/.tsv oeffnen.",
            "/M row|col a b [n]     Zeilen oder Spalten verschieben.",
            "/O screen|file path    Auf Bildschirm, .txt, .csv, .tsv oder .pdf ausgeben.",
            "/P [range]             Zellen vor Bearbeitung schuetzen (Standard: Auswahl).",
            "/Q                     Beenden.",
            "/REDO                  Letzte rueckgaengig gemachte Aktion wiederholen.",
            "/R src dst             Formeln/Inhalte zum Ziel replizieren.",
            "/REPLACE old new [range] Rohtext in Zellen ersetzen.",
            "/S [file]              Speichern oder das Menue speichern/speichern unter/speichern+beenden oeffnen.",
            "/SAVEAS file           Blatt in neue Datei speichern.",
            "/TAB                   Tabs verwalten (umbenennen, duplizieren, schliessen, verschieben).",
            "/T rows [cols]         Titelzeilen und -spalten fixieren.",
            "/U [range]             Schutz entfernen (Standard: Auswahl).",
            "/W                     Befehlshilfe oeffnen.",
            "/X file                Befehle aus Datei ausfuehren.",
            "/Z                     Gesamten Arbeitsbereich loeschen.",
            "/GO cell               Zu einer Zelle springen.",
        ]
    if language_code == "it":
        return [
            "/A range [col] [desc]  Ordina le righe di un intervallo per offset di colonna.",
            "/B [range]             Svuota una cella o un intervallo (selezione predefinita).",
            "/C src dst             Copia un intervallo in una destinazione (selezione predefinita).",
            "/D row|col index [n]   Elimina righe o colonne (selezione predefinita).",
            "/E                     Apri impostazioni.",
            "/F                     Apri il menu formato.",
            "/F DATE                Imposta il formato data per tutto il foglio.",
            "/F TIME                Imposta il formato orario (24h, 24h-seconds, 12h, 12h-seconds).",
            "/FIND text [range]     Trova la prossima cella corrispondente.",
            "/G width n             Imposta la larghezza globale delle colonne.",
            "/G width col n         Imposta la larghezza di una colonna, per es. /G width B 18.",
            "/H                     Apri gli argomenti di aiuto.",
            "/I row|col index [n]   Inserisci righe o colonne.",
            "/J left|centre|right [range]  Allinea a sinistra, centro o destra.",
            "/L                     Sfoglia i recenti o apri il selettore per .tss/.csv/.tsv.",
            "/M row|col a b [n]     Sposta righe o colonne.",
            "/O screen|file path    Esporta su schermo, .txt, .csv, .tsv o .pdf.",
            "/P [range]             Proteggi le celle dalle modifiche (selezione predefinita).",
            "/Q                     Esci.",
            "/REDO                  Ripristina l'ultima azione annullata.",
            "/R src dst             Replica formule/contenuti nella destinazione.",
            "/REPLACE old new [range] Sostituisce il testo grezzo nelle celle.",
            "/S [file]              Salva o apre il menu salva/salva con nome/salva+esci.",
            "/SAVEAS file           Salva il foglio in un nuovo file.",
            "/TAB                   Gestisci schede (rinomina, duplica, chiudi, sposta).",
            "/T rows [cols]         Blocca righe e colonne del titolo.",
            "/U [range]             Rimuovi protezione (selezione predefinita).",
            "/W                     Apri l'aiuto dei comandi.",
            "/X file                Esegui comandi da un file.",
            "/Z                     Cancella l'intero spazio di lavoro.",
            "/GO cell               Vai a una cella.",
        ]
    if language_code == "es":
        return [
            "/A range [col] [desc]  Ordena las filas de un rango por desplazamiento de columna.",
            "/B [range]             Vacia una celda o un rango (seleccion por defecto).",
            "/C src dst             Copia un rango a un destino (seleccion por defecto).",
            "/D row|col index [n]   Elimina filas o columnas (seleccion por defecto).",
            "/E                     Abre configuracion.",
            "/F                     Abre el menu de formato.",
            "/F DATE                Establece el formato de fecha para toda la hoja.",
            "/F TIME                Establece el formato hora (24h, 24h-seconds, 12h, 12h-seconds).",
            "/FIND text [range]     Busca la siguiente celda coincidente.",
            "/G width n             Establece el ancho global de columna.",
            "/G width col n         Establece el ancho de una columna, por ejemplo /G width B 18.",
            "/H                     Abre los temas de ayuda.",
            "/I row|col index [n]   Inserta filas o columnas.",
            "/J left|centre|right [range]  Alinea a izquierda, centro o derecha.",
            "/L                     Explora recientes o abre el selector para .tss/.csv/.tsv.",
            "/M row|col a b [n]     Mueve filas o columnas.",
            "/O screen|file path    Salida a pantalla, .txt, .csv, .tsv o .pdf.",
            "/P [range]             Protege celdas contra edicion (seleccion por defecto).",
            "/Q                     Salir.",
            "/REDO                  Rehace la ultima accion deshecha.",
            "/R src dst             Replica formulas/contenidos al destino.",
            "/REPLACE old new [range] Reemplaza texto bruto en celdas.",
            "/S [file]              Guarda o abre el menu guardar/guardar como/guardar+salir.",
            "/SAVEAS file           Guarda la hoja en un archivo nuevo.",
            "/TAB                   Gestiona pestanas (renombrar, duplicar, cerrar, mover).",
            "/T rows [cols]         Inmoviliza filas y columnas de titulo.",
            "/U [range]             Quita la proteccion (seleccion por defecto).",
            "/W                     Abre la ayuda de comandos.",
            "/X file                Ejecuta comandos desde un archivo.",
            "/Z                     Borra todo el espacio de trabajo.",
            "/GO cell               Ir a una celda.",
        ]
    if language_code == "nl":
        return [
            "/A range [col] [desc]  Sorteer rijen in een bereik op kolomoffset.",
            "/B [range]             Maak een cel of bereik leeg (standaard: selectie).",
            "/C src dst             Kopieer een bereik naar een doel (standaard: selectie).",
            "/D row|col index [n]   Verwijder rijen of kolommen (standaard: selectie).",
            "/E                     Open instellingen.",
            "/F                     Open het opmaakmenu.",
            "/F DATE                Stel het datumformaat voor het hele blad in.",
            "/F TIME                Stel het tijdformaat in (24h, 24h-seconds, 12h, 12h-seconds).",
            "/FIND text [range]     Zoek de volgende passende cel.",
            "/G width n             Stel globale kolombreedte in.",
            "/G width col n         Stel breedte van een kolom in, bv. /G width B 18.",
            "/H                     Open hulponderwerpen.",
            "/I row|col index [n]   Voeg rijen of kolommen in.",
            "/J left|centre|right [range]  Lijn links, midden of rechts uit.",
            "/L                     Blader door recente bestanden of open de kiezer voor .tss/.csv/.tsv.",
            "/M row|col a b [n]     Verplaats rijen of kolommen.",
            "/O screen|file path    Uitvoer naar scherm, .txt, .csv, .tsv of .pdf.",
            "/P [range]             Bescherm cellen tegen bewerken (standaard: selectie).",
            "/Q                     Afsluiten.",
            "/REDO                  Herhaal de laatst ongedaan gemaakte actie.",
            "/R src dst             Reproduceer formules/inhoud naar doel.",
            "/REPLACE old new [range] Vervang ruwe tekst in cellen.",
            "/S [file]              Opslaan of het menu opslaan/opslaan als/opslaan+afsluiten openen.",
            "/SAVEAS file           Blad opslaan naar nieuw bestand.",
            "/TAB                   Tabs beheren (hernoemen, dupliceren, sluiten, verplaatsen).",
            "/T rows [cols]         Titelrijen en -kolommen vastzetten.",
            "/U [range]             Bescherming verwijderen (standaard: selectie).",
            "/W                     Opdracht-help openen.",
            "/X file                Voer opdrachten uit vanuit bestand.",
            "/Z                     Wis de volledige werkruimte.",
            "/GO cell               Ga naar een cel.",
        ]
    return COMMAND_HELP_LINES


def get_key_help_lines(language_code: str) -> list[str]:
    if language_code == "fr":
        return [
            "Fleches ou hjkl         Deplacer la cellule active.",
            "Maj+fleches             Etendre une selection rectangulaire.",
            "Maj+Espace              Selectionne la ligne courante si le terminal le permet.",
            "Ctrl+Espace             Selectionne la colonne courante.",
            "Entree                  Modifier la cellule, enregistrer, puis descendre.",
            "Suppr                   Effacer le contenu de la cellule actuelle.",
            "Ctrl+C                  Copier la cellule ou la selection.",
            "Ctrl+V ou Ctrl+Y        Coller la cellule ou la selection copiee.",
            "Ctrl+S                  Enregistrer la feuille actuelle.",
            "Ctrl+Q                  Quitter.",
            "Ctrl+Z                  Annuler la derniere action.",
            "Ctrl+E ou F2            Modifier la cellule dans la barre de formule.",
            "Ctrl+R                  Retablir la derniere action annulee.",
            "Ctrl+B                  Appliquer le format gras.",
            "Ctrl+U                  Appliquer le format souligne.",
            "Ctrl+I                  Appliquer le format italique.",
            "F1                      Affiche/masque le resume des touches.",
            "/                       Ouvrir le menu des commandes.",
            "/H                      Ouvrir les rubriques d'aide.",
            "Echap                   Annuler l'invite ou le menu.",
            "Alt+=                   Inserer SOMME des cellules numeriques au-dessus.",
            "Clic souris             Deplacer la cellule active.",
            "Glisser souris          Selectionner une plage rectangulaire.",
            "Molette/pave tactile    Defiler verticalement.",
            "Clic onglet             Changer de fichier ouvert.",
            "Clic engrenage bas-droit Ouvrir les parametres.",
            "Clic entete ligne/col.  Selectionne toute la ligne/colonne; recliquez pour les actions.",
            "Stats selection         Barre du bas: compte/somme/moyenne (numeriques).",
            "Selecteur fichiers: taper Filtre les elements visibles.",
            "Selecteur fichiers: .   Affiche ou masque les fichiers caches.",
            "Selecteur fichiers: ..  Remonte au dossier parent.",
            "Selecteur fichiers: s   Change le tri nom/date/type.",
            "Selecteur fichiers: p   Saisit un chemin a ouvrir directement.",
            "Selecteur fichiers: n   Cree un nouveau dossier.",
            "Selecteur fichiers: r   Renomme le fichier ou dossier selectionne.",
            "Selecteur fichiers: Suppr Supprime le fichier ou dossier selectionne.",
        ]
    if language_code == "de":
        return [
            "Pfeile oder hjkl        Aktive Zelle bewegen.",
            "Umschalt+Pfeile         Rechteckige Auswahl erweitern.",
            "Umschalt+Leertaste      Aktuelle Zeile waehlen, falls das Terminal es unterstuetzt.",
            "Ctrl+Leertaste          Aktuelle Spalte waehlen.",
            "Enter                   Zelle bearbeiten, speichern, dann nach unten.",
            "Entf                    Inhalt der aktuellen Zelle loeschen.",
            "Ctrl+C                  Aktuelle Zelle oder Auswahl kopieren.",
            "Ctrl+V oder Ctrl+Y      Kopierte Zelle oder Auswahl einfuegen.",
            "Ctrl+S                  Aktuelles Blatt speichern.",
            "Ctrl+Q                  Beenden.",
            "Ctrl+Z                  Letzte Aktion rueckgaengig machen.",
            "Ctrl+E oder F2          Zelle in der Formelleiste bearbeiten.",
            "Ctrl+R                  Letzte rueckgaengig gemachte Aktion wiederholen.",
            "Ctrl+B                  Fettformat anwenden.",
            "Ctrl+U                  Unterstreichungsformat anwenden.",
            "Ctrl+I                  Kursivformat anwenden.",
            "F1                      Tastenkurzhilfe ein/ausblenden.",
            "/                       Befehlsmenue oeffnen.",
            "/H                      Hilfethemen oeffnen.",
            "Esc                     Eingabe oder Menue abbrechen.",
            "Alt+=                   SUMME der numerischen Zellen darueber einfuegen.",
            "Mausklick               Aktive Zelle bewegen.",
            "Mausziehen              Rechteckigen Bereich auswaehlen.",
            "Mausrad/Touchpad        Vertikal scrollen.",
            "Klick auf Tab           Zwischen offenen Dateien wechseln.",
            "Klick auf Zahnrad unten rechts Einstellungen oeffnen.",
            "Klick auf Zeilen/Spaltenkopf Waehlt ganze Zeile/Spalte; erneut klicken fuer Aktionen.",
            "Auswahlwerte            Untere Leiste: Anzahl/Summe/Mittel (numerisch).",
            "Dateiwaehler: tippen    Sichtbare Eintraege filtern.",
            "Dateiwaehler: .         Versteckte Dateien ein/ausblenden.",
            "Dateiwaehler: ..        Zum uebergeordneten Ordner gehen.",
            "Dateiwaehler: s         Sortierung Name/Zeit/Typ wechseln.",
            "Dateiwaehler: p         Pfad direkt zum Oeffnen eingeben.",
            "Dateiwaehler: n         Neuen Ordner erstellen.",
            "Dateiwaehler: r         Ausgewaehlte Datei oder Ordner umbenennen.",
            "Dateiwaehler: Entf      Ausgewaehlte Datei oder Ordner loeschen.",
        ]
    if language_code == "it":
        return [
            "Frecce o hjkl           Sposta la cella attiva.",
            "Maiusc+frecce           Estende una selezione rettangolare.",
            "Maiusc+Spazio           Seleziona la riga corrente se il terminale lo supporta.",
            "Ctrl+Spazio             Seleziona la colonna corrente.",
            "Invio                   Modifica la cella, salva e scendi.",
            "Canc                    Cancella il contenuto della cella corrente.",
            "Ctrl+C                  Copia la cella o la selezione.",
            "Ctrl+V o Ctrl+Y         Incolla la cella o la selezione copiata.",
            "Ctrl+S                  Salva il foglio corrente.",
            "Ctrl+Q                  Esci.",
            "Ctrl+Z                  Annulla l'ultima azione.",
            "Ctrl+E o F2             Modifica la cella nella barra formula.",
            "Ctrl+R                  Ripristina l'ultima azione annullata.",
            "Ctrl+B                  Applica il formato grassetto.",
            "Ctrl+U                  Applica il formato sottolineato.",
            "Ctrl+I                  Applica il formato corsivo.",
            "F1                      Mostra/nasconde il riepilogo tasti.",
            "/                       Apri il menu comandi.",
            "/H                      Apri gli argomenti di aiuto.",
            "Esc                     Annulla prompt o menu.",
            "Alt+=                   Inserisce SOMMA delle celle numeriche sopra.",
            "Clic mouse              Sposta la cella attiva.",
            "Trascina mouse          Seleziona un intervallo rettangolare.",
            "Rotella mouse/touchpad  Scorre verticalmente.",
            "Clic sulla scheda       Cambia file aperto.",
            "Clic ingranaggio in basso a destra Apre impostazioni.",
            "Clic intestazione riga/colonna Seleziona tutta la riga/colonna; clicca di nuovo per le azioni.",
            "Statistiche selezione   Barra in basso: conteggio/somma/media (numerici).",
            "Selettore file: digita  Filtra gli elementi visibili.",
            "Selettore file: .       Mostra o nasconde i file nascosti.",
            "Selettore file: ..      Sale alla cartella superiore.",
            "Selettore file: s       Cambia ordinamento nome/data/tipo.",
            "Selettore file: p       Inserisce un percorso da aprire direttamente.",
            "Selettore file: n       Crea una nuova cartella.",
            "Selettore file: r       Rinomina il file o la cartella selezionata.",
            "Selettore file: Canc    Elimina il file o la cartella selezionata.",
        ]
    if language_code == "es":
        return [
            "Flechas o hjkl          Mueve la celda activa.",
            "Mayus+flechas           Amplia una seleccion rectangular.",
            "Mayus+Espacio           Selecciona la fila actual si el terminal lo permite.",
            "Ctrl+Espacio            Selecciona la columna actual.",
            "Intro                   Edita la celda, guarda y baja.",
            "Supr                    Borra el contenido de la celda actual.",
            "Ctrl+C                  Copia la celda o la seleccion.",
            "Ctrl+V o Ctrl+Y         Pega la celda o la seleccion copiada.",
            "Ctrl+S                  Guarda la hoja actual.",
            "Ctrl+Q                  Salir.",
            "Ctrl+Z                  Deshace la ultima accion.",
            "Ctrl+E o F2             Edita la celda en la barra de formulas.",
            "Ctrl+R                  Rehace la ultima accion deshecha.",
            "Ctrl+B                  Aplica formato en negrita.",
            "Ctrl+U                  Aplica formato subrayado.",
            "Ctrl+I                  Aplica formato cursiva.",
            "F1                      Alterna resumen de teclas.",
            "/                       Abre el menu de comandos.",
            "/H                      Abre los temas de ayuda.",
            "Esc                     Cancela el aviso o menu.",
            "Alt+=                   Inserta SUMA de celdas numericas de arriba.",
            "Clic del raton          Mueve la celda activa.",
            "Arrastre del raton      Selecciona un rango rectangular.",
            "Rueda/touchpad          Desplaza verticalmente.",
            "Clic en pestana         Cambia entre archivos abiertos.",
            "Clic engranaje inferior derecho Abre configuracion.",
            "Clic cabecera fila/columna Selecciona toda la fila/columna; haz clic otra vez para acciones.",
            "Stats seleccion         Barra inferior: conteo/suma/media (numericos).",
            "Selector archivos: escribir Filtra los elementos visibles.",
            "Selector archivos: .    Muestra u oculta archivos ocultos.",
            "Selector archivos: ..   Sube a la carpeta superior.",
            "Selector archivos: s    Cambia orden por nombre/fecha/tipo.",
            "Selector archivos: p    Escribe una ruta para abrir directamente.",
            "Selector archivos: n    Crea una carpeta nueva.",
            "Selector archivos: r    Renombra el archivo o carpeta seleccionados.",
            "Selector archivos: Supr Elimina el archivo o carpeta seleccionados.",
        ]
    if language_code == "nl":
        return [
            "Pijlen of hjkl          Verplaats de actieve cel.",
            "Shift+pijlen            Vergroot een rechthoekige selectie.",
            "Shift+Spatie            Selecteer de huidige rij als de terminal dit ondersteunt.",
            "Ctrl+Spatie             Selecteer de huidige kolom.",
            "Enter                   Bewerk cel, sla op en ga omlaag.",
            "Delete                  Wis inhoud van de huidige cel.",
            "Ctrl+C                  Kopieer de cel of selectie.",
            "Ctrl+V of Ctrl+Y        Plak de gekopieerde cel of selectie.",
            "Ctrl+S                  Sla het huidige blad op.",
            "Ctrl+Q                  Afsluiten.",
            "Ctrl+Z                  Maak de laatste actie ongedaan.",
            "Ctrl+E of F2            Bewerk de cel in de formulebalk.",
            "Ctrl+R                  Herhaal de laatst ongedaan gemaakte actie.",
            "Ctrl+B                  Pas vet formaat toe.",
            "Ctrl+U                  Pas onderstreept formaat toe.",
            "Ctrl+I                  Pas cursief formaat toe.",
            "F1                      Toon/verberg toetsensamenvatting.",
            "/                       Open het opdrachtenmenu.",
            "/H                      Open hulponderwerpen.",
            "Esc                     Annuleer prompt of menu.",
            "Alt+=                   Voeg SOM toe van numerieke cellen erboven.",
            "Muisklik                Verplaats actieve cel.",
            "Muis slepen             Selecteer een rechthoekig bereik.",
            "Muiswiel/touchpad       Scroll verticaal.",
            "Klik op tabblad         Wissel tussen open bestanden.",
            "Klik tandwiel rechtsonder Open instellingen.",
            "Klik rij/kolomkop       Selecteer hele rij/kolom; klik opnieuw voor acties.",
            "Selectiestatistiek      Onderbalk: aantal/som/gem (numeriek).",
            "Bestandskiezer: typen   Filter zichtbare items.",
            "Bestandskiezer: .       Toon of verberg verborgen bestanden.",
            "Bestandskiezer: ..      Ga naar de bovenliggende map.",
            "Bestandskiezer: s       Wissel sortering naam/tijd/type.",
            "Bestandskiezer: p       Voer direct een pad in om te openen.",
            "Bestandskiezer: n       Maak een nieuwe map aan.",
            "Bestandskiezer: r       Hernoem het geselecteerde bestand of de map.",
            "Bestandskiezer: Delete  Verwijder het geselecteerde bestand of de map.",
        ]
    return KEY_HELP_LINES


def get_formula_help_lines(language_code: str) -> list[str]:
    if language_code == "fr":
        return [
            "Maths/Stats: ABS, AVERAGE, AVG, COS, COUNT, COUNTIF, INT, MAX, MIN, MOD, ROUND, SIN, SQRT, SUM, SUMIF, TAN",
            "Logique: AND, IF(condition, valeur_si_vrai, valeur_si_faux), IFERROR, NOT, OR",
            "Texte: CONCAT, LEFT, LEN, LOWER, MID, PROPER, RIGHT, TEXT, TRIM, UPPER, VALUE",
            "Donnees: HLOOKUP, INDEX, LOOKUP, MATCH, SUMIF, VLOOKUP, XLOOKUP",
            "Dates: DATE, TODAY, YEAR, MONTH, DAY, DATEDIFF, WEEKDAY",
            "Affichage/saisie des dates: /F DATE puis choisir european, uk, us ou ansi",
            "Saisie de formule: les fleches pointent vers les cellules, : commence une plage, Entree valide/ferme les parentheses",
            'Criteres COUNTIF/SUMIF: valeurs exactes comme "Fred" ou operateurs comme ">10", "<=5", "<>0".',
            "",
            "Exemples:",
            "=SUM(A1:A10)",
            "=AND(A1>0, B1>0)",
            "=AVERAGE(B1:B5)",
            "=ROUND(C1/7, 2)",
            "=ABS(D1)",
            "=COS(0)",
            "=SIN(0)",
            "=MOD(A1, 7)",
            '=COUNTIF(A2:A10, "Fred")',
            "=IF(A1=10, 1, 0)",
            "=IF(B2<>0, B1/B2, 0)",
            '=IFERROR(VLOOKUP("Fred", A2:C10, 2), "manquant")',
            '=CONCAT(LEFT(A1, 3), "-", RIGHT(B1, 2))',
            '=TEXT(TODAY(), "dd/mm/yyyy")',
            '=LOOKUP("Fred", A2:A10, B2:B10)',
            '=XLOOKUP("Fred", A2:A10, B2:B10, "manquant")',
            '=SUMIF(B2:B10, ">10", C2:C10)',
            '=SUMIF(A2:A10, "Fred", B2:B10)',
            '=MATCH("Fred", A2:A10)',
            '=INDEX(B2:B10, 3)',
            '=TRIM("  bonjour   monde  ")',
            '=UPPER("fred")',
            '=LOWER("FRED")',
            '=PROPER("compte bancaire")',
            '=VLOOKUP("Fred", A2:C10, 2)',
            '=HLOOKUP("Q2", A1:D4, 3)',
            "=DATE(2026, 4, 5)",
            "=TODAY()",
            "=YEAR(A1)",
            "=MONTH(A1)",
            "=DAY(A1)",
            "=DATEDIFF(A1, B1)",
            "=WEEKDAY(A1)",
            "",
            "Refs absolues: $A$1  $A1  A$1",
        ]
    if language_code == "de":
        return [
            "Math/Statistik: ABS, AVERAGE, AVG, COS, COUNT, COUNTIF, INT, MAX, MIN, MOD, ROUND, SIN, SQRT, SUM, SUMIF, TAN",
            "Logik: AND, IF(Bedingung, dann_Wert, sonst_Wert), IFERROR, NOT, OR",
            "Text: CONCAT, LEFT, LEN, LOWER, MID, PROPER, RIGHT, TEXT, TRIM, UPPER, VALUE",
            "Daten: HLOOKUP, INDEX, LOOKUP, MATCH, SUMIF, VLOOKUP, XLOOKUP",
            "Datum: DATE, TODAY, YEAR, MONTH, DAY, DATEDIFF, WEEKDAY",
            "Datumsanzeige/-eingabe: /F DATE und dann european, uk, us oder ansi waehlen",
            "Formeleingabe: Pfeile zeigen auf Zellen, : startet einen Bereich, Enter uebernimmt/schliesst Klammern",
            'COUNTIF/SUMIF-Kriterien: exakte Werte wie "Fred" oder Operatoren wie ">10", "<=5", "<>0".',
            "",
            "Beispiele:",
            "=SUM(A1:A10)",
            "=AND(A1>0, B1>0)",
            "=AVERAGE(B1:B5)",
            "=ROUND(C1/7, 2)",
            "=ABS(D1)",
            "=COS(0)",
            "=SIN(0)",
            "=MOD(A1, 7)",
            '=COUNTIF(A2:A10, "Fred")',
            "=IF(A1=10, 1, 0)",
            "=IF(B2<>0, B1/B2, 0)",
            '=IFERROR(VLOOKUP("Fred", A2:C10, 2), "fehlt")',
            '=CONCAT(LEFT(A1, 3), "-", RIGHT(B1, 2))',
            '=TEXT(TODAY(), "dd/mm/yyyy")',
            '=LOOKUP("Fred", A2:A10, B2:B10)',
            '=XLOOKUP("Fred", A2:A10, B2:B10, "fehlt")',
            '=SUMIF(B2:B10, ">10", C2:C10)',
            '=SUMIF(A2:A10, "Fred", B2:B10)',
            '=MATCH("Fred", A2:A10)',
            '=INDEX(B2:B10, 3)',
            '=TRIM("  hallo   welt  ")',
            '=UPPER("fred")',
            '=LOWER("FRED")',
            '=PROPER("bank konto")',
            '=VLOOKUP("Fred", A2:C10, 2)',
            '=HLOOKUP("Q2", A1:D4, 3)',
            "=DATE(2026, 4, 5)",
            "=TODAY()",
            "=YEAR(A1)",
            "=MONTH(A1)",
            "=DAY(A1)",
            "=DATEDIFF(A1, B1)",
            "=WEEKDAY(A1)",
            "",
            "Absolute Bezuge: $A$1  $A1  A$1",
        ]
    if language_code == "it":
        return [
            "Matematica/Statistiche: ABS, AVERAGE, AVG, COS, COUNT, COUNTIF, INT, MAX, MIN, MOD, ROUND, SIN, SQRT, SUM, SUMIF, TAN",
            "Logica: AND, IF(condizione, valore_se_vero, valore_se_falso), IFERROR, NOT, OR",
            "Testo: CONCAT, LEFT, LEN, LOWER, MID, PROPER, RIGHT, TEXT, TRIM, UPPER, VALUE",
            "Dati: HLOOKUP, INDEX, LOOKUP, MATCH, SUMIF, VLOOKUP, XLOOKUP",
            "Date: DATE, TODAY, YEAR, MONTH, DAY, DATEDIFF, WEEKDAY",
            "Visualizzazione/inserimento data: /F DATE poi scegli european, uk, us o ansi",
            "Inserimento formula: le frecce puntano alle celle, : avvia un intervallo, Invio conferma/chiude le parentesi",
            'Criteri COUNTIF/SUMIF: valori esatti come "Fred" o operatori come ">10", "<=5", "<>0".',
            "",
            "Esempi:",
            "=SUM(A1:A10)",
            "=AND(A1>0, B1>0)",
            "=AVERAGE(B1:B5)",
            "=ROUND(C1/7, 2)",
            "=ABS(D1)",
            "=COS(0)",
            "=SIN(0)",
            "=MOD(A1, 7)",
            '=COUNTIF(A2:A10, "Fred")',
            "=IF(A1=10, 1, 0)",
            "=IF(B2<>0, B1/B2, 0)",
            '=IFERROR(VLOOKUP("Fred", A2:C10, 2), "manca")',
            '=CONCAT(LEFT(A1, 3), "-", RIGHT(B1, 2))',
            '=TEXT(TODAY(), "dd/mm/yyyy")',
            '=LOOKUP("Fred", A2:A10, B2:B10)',
            '=XLOOKUP("Fred", A2:A10, B2:B10, "manca")',
            '=SUMIF(B2:B10, ">10", C2:C10)',
            '=SUMIF(A2:A10, "Fred", B2:B10)',
            '=MATCH("Fred", A2:A10)',
            '=INDEX(B2:B10, 3)',
            '=TRIM("  ciao   mondo  ")',
            '=UPPER("fred")',
            '=LOWER("FRED")',
            '=PROPER("conto banca")',
            '=VLOOKUP("Fred", A2:C10, 2)',
            '=HLOOKUP("Q2", A1:D4, 3)',
            "=DATE(2026, 4, 5)",
            "=TODAY()",
            "=YEAR(A1)",
            "=MONTH(A1)",
            "=DAY(A1)",
            "=DATEDIFF(A1, B1)",
            "=WEEKDAY(A1)",
            "",
            "Riferimenti assoluti: $A$1  $A1  A$1",
        ]
    if language_code == "es":
        return [
            "Mat/Estad: ABS, AVERAGE, AVG, COS, COUNT, COUNTIF, INT, MAX, MIN, MOD, ROUND, SIN, SQRT, SUM, SUMIF, TAN",
            "Logica: AND, IF(condicion, valor_si, valor_no), IFERROR, NOT, OR",
            "Texto: CONCAT, LEFT, LEN, LOWER, MID, PROPER, RIGHT, TEXT, TRIM, UPPER, VALUE",
            "Datos: HLOOKUP, INDEX, LOOKUP, MATCH, SUMIF, VLOOKUP, XLOOKUP",
            "Fechas: DATE, TODAY, YEAR, MONTH, DAY, DATEDIFF, WEEKDAY",
            "Visualizacion/entrada de fecha: /F DATE y luego elegir european, uk, us o ansi",
            "Entrada de formulas: las flechas apuntan a celdas, : inicia un rango, Enter acepta/cierra parentesis",
            'Criterios COUNTIF/SUMIF: valores exactos como "Fred" u operadores como ">10", "<=5", "<>0".',
            "",
            "Ejemplos:",
            "=SUM(A1:A10)",
            "=AND(A1>0, B1>0)",
            "=AVERAGE(B1:B5)",
            "=ROUND(C1/7, 2)",
            "=ABS(D1)",
            "=COS(0)",
            "=SIN(0)",
            "=MOD(A1, 7)",
            '=COUNTIF(A2:A10, "Fred")',
            "=IF(A1=10, 1, 0)",
            "=IF(B2<>0, B1/B2, 0)",
            '=IFERROR(VLOOKUP("Fred", A2:C10, 2), "falta")',
            '=CONCAT(LEFT(A1, 3), "-", RIGHT(B1, 2))',
            '=TEXT(TODAY(), "dd/mm/yyyy")',
            '=LOOKUP("Fred", A2:A10, B2:B10)',
            '=XLOOKUP("Fred", A2:A10, B2:B10, "falta")',
            '=SUMIF(B2:B10, ">10", C2:C10)',
            '=SUMIF(A2:A10, "Fred", B2:B10)',
            '=MATCH("Fred", A2:A10)',
            '=INDEX(B2:B10, 3)',
            '=TRIM("  hola   mundo  ")',
            '=UPPER("fred")',
            '=LOWER("FRED")',
            '=PROPER("cuenta banco")',
            '=VLOOKUP("Fred", A2:C10, 2)',
            '=HLOOKUP("Q2", A1:D4, 3)',
            "=DATE(2026, 4, 5)",
            "=TODAY()",
            "=YEAR(A1)",
            "=MONTH(A1)",
            "=DAY(A1)",
            "=DATEDIFF(A1, B1)",
            "=WEEKDAY(A1)",
            "",
            "Refs absolutas: $A$1  $A1  A$1",
        ]
    if language_code == "nl":
        return [
            "Wisk/Stats: ABS, AVERAGE, AVG, COS, COUNT, COUNTIF, INT, MAX, MIN, MOD, ROUND, SIN, SQRT, SUM, SUMIF, TAN",
            "Logica: AND, IF(voorwaarde, dan_waarde, anders_waarde), IFERROR, NOT, OR",
            "Tekst: CONCAT, LEFT, LEN, LOWER, MID, PROPER, RIGHT, TEXT, TRIM, UPPER, VALUE",
            "Data: HLOOKUP, INDEX, LOOKUP, MATCH, SUMIF, VLOOKUP, XLOOKUP",
            "Datums: DATE, TODAY, YEAR, MONTH, DAY, DATEDIFF, WEEKDAY",
            "Datumweergave/invoer: /F DATE en kies daarna european, uk, us of ansi",
            "Formule-invoer: pijlen wijzen naar cellen, : start een bereik, Enter bevestigt/sluit haakjes",
            'COUNTIF/SUMIF-criteria: exacte waarden zoals "Fred" of operatoren zoals ">10", "<=5", "<>0".',
            "",
            "Voorbeelden:",
            "=SUM(A1:A10)",
            "=AND(A1>0, B1>0)",
            "=AVERAGE(B1:B5)",
            "=ROUND(C1/7, 2)",
            "=ABS(D1)",
            "=COS(0)",
            "=SIN(0)",
            "=MOD(A1, 7)",
            '=COUNTIF(A2:A10, "Fred")',
            "=IF(A1=10, 1, 0)",
            "=IF(B2<>0, B1/B2, 0)",
            '=IFERROR(VLOOKUP("Fred", A2:C10, 2), "mist")',
            '=CONCAT(LEFT(A1, 3), "-", RIGHT(B1, 2))',
            '=TEXT(TODAY(), "dd/mm/yyyy")',
            '=LOOKUP("Fred", A2:A10, B2:B10)',
            '=XLOOKUP("Fred", A2:A10, B2:B10, "mist")',
            '=SUMIF(B2:B10, ">10", C2:C10)',
            '=SUMIF(A2:A10, "Fred", B2:B10)',
            '=MATCH("Fred", A2:A10)',
            '=INDEX(B2:B10, 3)',
            '=TRIM("  hallo   wereld  ")',
            '=UPPER("fred")',
            '=LOWER("FRED")',
            '=PROPER("bank rekening")',
            '=VLOOKUP("Fred", A2:C10, 2)',
            '=HLOOKUP("Q2", A1:D4, 3)',
            "=DATE(2026, 4, 5)",
            "=TODAY()",
            "=YEAR(A1)",
            "=MONTH(A1)",
            "=DAY(A1)",
            "=DATEDIFF(A1, B1)",
            "=WEEKDAY(A1)",
            "",
            "Absolute verwijzingen: $A$1  $A1  A$1",
        ]
    return FORMULA_HELP_LINES


def parse_command(text: str) -> Command:
    cleaned = text.strip()
    if cleaned.startswith("/"):
        cleaned = cleaned[1:]
    parts = shlex.split(cleaned)
    if not parts:
        return Command(name="help", args=[])
    name = ALIASES.get(parts[0].lower(), parts[0].lower())
    return Command(name=name, args=parts[1:])
